# Generated by Django 4.2.7 on 2023-12-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
