# Generated by Django 4.2.7 on 2023-12-11 08:39

from django.db import migrations
import exclusivebooleanfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_course_discount_price_alter_course_is_free"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="is_free",
            field=exclusivebooleanfield.fields.ExclusiveBooleanField(
                default=False, on=("is_saved",)
            ),
        ),
    ]
