# Generated by Django 4.2.7 on 2023-12-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_comment_course_alter_lesson_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="blog.course",
            ),
        ),
    ]
